//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMapTry.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GMapTry.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dot {
            get {
                object obj = ResourceManager.GetObject("dot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dotGreen {
            get {
                object obj = ResourceManager.GetObject("dotGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hotspot {
            get {
                object obj = ResourceManager.GetObject("hotspot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33.6173627,-85.7274272
        ///33.6179830,-85.7194030
        ///33.6118243,-85.7809944
        ///33.6110146,-85.7902104
        ///33.6182120,-85.7191030
        ///33.6176350,-85.7270238
        ///33.6050446,-85.8356960
        ///33.6050225,-85.8317634
        ///33.6050154,-85.8281326
        ///33.6052345,-85.8341554
        ///33.6052155,-85.8267588
        ///33.6106347,-85.7909738
        ///33.6115304,-85.7809127
        ///33.5860040,-85.8755690
        ///33.5861250,-85.8752140
        ///33.5865040,-85.8742630
        ///33.5877660,-85.8714530
        ///33.5884130,-85.8700400
        ///33.5890350,-85.8686500
        ///33.5896590,-85.8672730
        ///33.5899690,-85.8665870
        ///33.59117 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string I20 {
            get {
                return ResourceManager.GetString("I20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34.1714800,-88.0670620
        ///34.1633960,-88.0624350
        ///34.1708130,-88.0663410
        ///34.0722260,-87.9810820
        ///34.0713640,-87.9706790
        ///34.0879390,-88.0038210
        ///34.0933880,-88.0108360
        ///34.0935800,-88.0115430
        ///34.0884310,-88.0048830
        ///34.1218440,-88.0495740
        ///34.1182290,-88.0407520
        ///34.1187820,-88.0414360
        ///34.1217860,-88.0487520
        ///33.9909290,-87.7810710
        ///33.9889020,-87.7727150
        ///33.9912880,-87.7812970
        ///34.0146770,-87.8378120
        ///34.0093248,-87.8307728
        ///34.0093473,-87.8303279
        ///34.0433816,-87.8939110
        ///34.0388960,-87.8838831
        ///34.04348 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string I22 {
            get {
                return ResourceManager.GetString("I22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33.5952810,-86.6519280
        ///33.3849260,-86.8054390
        ///33.3839300,-86.8076180
        ///33.3339140,-86.9717060
        ///33.3831700,-86.8092820
        ///33.3832240,-86.8096930
        ///33.4479410,-86.7241680
        ///33.3853530,-86.8050560
        ///33.3905656,-86.7930557
        ///33.4434860,-86.7289010
        ///33.4421630,-86.7303990
        ///33.4421927,-86.7306873
        ///33.3326470,-86.9985350
        ///33.4380000,-86.7351000
        ///33.5283350,-86.6573190
        ///33.5283014,-86.6568973
        ///33.4461960,-86.7258030
        ///33.3939194,-86.7845413
        ///33.4923492,-86.7058555
        ///33.4912028,-86.7066139
        ///33.5787500,-86.6403680
        ///33.48761 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string I459 {
            get {
                return ResourceManager.GetString("I459", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34.1995649,-85.9453934
        ///34.1995198,-85.9443921
        ///33.9732970,-86.1131740
        ///33.9730970,-86.1131740
        ///34.0718045,-86.0271766
        ///34.0764305,-86.0242378
        ///33.9448685,-86.1656470
        ///33.9462840,-86.1618250
        ///33.9475860,-86.1585510
        ///33.9480950,-86.1571860
        ///33.9504830,-86.1518920
        ///33.9514970,-86.1498750
        ///33.9583970,-86.1374750
        ///33.9656810,-86.1245940
        ///33.9666970,-86.1228740
        ///33.9690970,-86.1192740
        ///33.9701970,-86.1176740
        ///33.9718970,-86.1150740
        ///33.9742760,-86.1113160
        ///33.9750870,-86.1100380
        ///33.9758460,-86.1088420
        ///33.97639 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string I59 {
            get {
                return ResourceManager.GetString("I59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32.5143610,-86.4291550
        ///32.5132430,-86.4292040
        ///32.5145420,-86.4308900
        ///32.5214450,-86.4372770
        ///32.5221730,-86.4381000
        ///32.5183930,-86.4359140
        ///32.5199020,-86.4378730
        ///32.5200210,-86.4380180
        ///32.5202040,-86.4382410
        ///32.5205160,-86.4385980
        ///32.5205870,-86.4386730
        ///32.5208390,-86.4389440
        ///32.5211710,-86.4392730
        ///32.5214930,-86.4395750
        ///32.5218640,-86.4398950
        ///32.5222220,-86.4401810
        ///32.5173660,-86.4326010
        ///32.5157180,-86.4324170
        ///32.5162710,-86.4331400
        ///32.5015450,-86.4178200
        ///32.5016780,-86.4178990
        ///32.50120 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string I65 {
            get {
                return ResourceManager.GetString("I65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vehicle {
            get {
                object obj = ResourceManager.GetObject("vehicle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
