//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMapTry.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GMapTry.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highway,AL79
        ///Lat,Lon
        ///33.9695620,-86.5882510
        ///34.0331590,-86.5749500
        ///34.0387240,-86.5757580
        ///34.1753800,-86.4619740
        ///34.1437000,-86.4912270
        ///33.8265590,-86.6685880
        ///34.1469250,-86.4893360
        ///34.0854250,-86.5397160
        ///34.1547790,-86.4833050
        ///34.1538080,-86.4840950
        ///33.8867050,-86.6420700
        ///33.8106020,-86.6749600
        ///34.1328980,-86.4979070
        ///34.1444520,-86.4907970
        ///34.1465860,-86.4895420
        ///34.1638400,-86.4741490
        ///34.1568250,-86.4815890
        ///34.1481270,-86.4885550
        ///34.1471270,-86.4892130
        ///34.1460040,-86.4898850
        ///33.962660 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AL79 {
            get {
                return ResourceManager.GetString("AL79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dot {
            get {
                object obj = ResourceManager.GetObject("dot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dotGreen {
            get {
                object obj = ResourceManager.GetObject("dotGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hotspot {
            get {
                object obj = ResourceManager.GetObject("hotspot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33.6173627,-85.7274272
        ///33.6179830,-85.7194030
        ///33.6118243,-85.7809944
        ///33.6110146,-85.7902104
        ///33.6182120,-85.7191030
        ///33.6176350,-85.7270238
        ///33.6050446,-85.8356960
        ///33.6050225,-85.8317634
        ///33.6050154,-85.8281326
        ///33.6052345,-85.8341554
        ///33.6052155,-85.8267588
        ///33.6106347,-85.7909738
        ///33.6115304,-85.7809127
        ///33.5860040,-85.8755690
        ///33.5861250,-85.8752140
        ///33.5865040,-85.8742630
        ///33.5877660,-85.8714530
        ///33.5884130,-85.8700400
        ///33.5890350,-85.8686500
        ///33.5896590,-85.8672730
        ///33.5899690,-85.8665870
        ///33.59117 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string I20 {
            get {
                return ResourceManager.GetString("I20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34.1714800,-88.0670620
        ///34.1633960,-88.0624350
        ///34.1708130,-88.0663410
        ///34.0722260,-87.9810820
        ///34.0713640,-87.9706790
        ///34.0879390,-88.0038210
        ///34.0933880,-88.0108360
        ///34.0935800,-88.0115430
        ///34.0884310,-88.0048830
        ///34.1218440,-88.0495740
        ///34.1182290,-88.0407520
        ///34.1187820,-88.0414360
        ///34.1217860,-88.0487520
        ///33.9909290,-87.7810710
        ///33.9889020,-87.7727150
        ///33.9912880,-87.7812970
        ///34.0146770,-87.8378120
        ///34.0093248,-87.8307728
        ///34.0093473,-87.8303279
        ///34.0433816,-87.8939110
        ///34.0388960,-87.8838831
        ///34.04348 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string I22 {
            get {
                return ResourceManager.GetString("I22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33.5952810,-86.6519280
        ///33.3849260,-86.8054390
        ///33.3839300,-86.8076180
        ///33.3339140,-86.9717060
        ///33.3831700,-86.8092820
        ///33.3832240,-86.8096930
        ///33.4479410,-86.7241680
        ///33.3853530,-86.8050560
        ///33.3905656,-86.7930557
        ///33.4434860,-86.7289010
        ///33.4421630,-86.7303990
        ///33.4421927,-86.7306873
        ///33.5933265,-86.6484316
        ///33.3326470,-86.9985350
        ///33.4380000,-86.7351000
        ///33.5283350,-86.6573190
        ///33.5283014,-86.6568973
        ///33.4461960,-86.7258030
        ///33.3939194,-86.7845413
        ///33.4923492,-86.7058555
        ///33.4912028,-86.7066139
        ///33.58890 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string I459 {
            get {
                return ResourceManager.GetString("I459", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34.2324727,-85.9151649
        ///34.2326616,-85.9157898
        ///34.5917490,-85.6431320
        ///34.5973960,-85.6396420
        ///34.4350310,-85.7517690
        ///34.4395840,-85.7459430
        ///34.5789900,-85.6545800
        ///34.5791090,-85.6547720
        ///34.2776110,-85.8780320
        ///34.2732950,-85.8810090
        ///34.4351930,-85.7512330
        ///34.4397610,-85.7454240
        ///34.5921370,-85.6424680
        ///34.5968380,-85.6396470
        ///34.6945200,-85.5709370
        ///34.6985690,-85.5671550
        ///34.6943070,-85.5714440
        ///34.6986390,-85.5674030
        ///34.4746507,-85.7146754
        ///34.4801422,-85.7098338
        ///34.2730590,-85.8804140
        ///34.27752 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string I59 {
            get {
                return ResourceManager.GetString("I59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32.5476460,-86.4555340
        ///32.5535890,-86.4607750
        ///32.5470380,-86.4552750
        ///32.5514710,-86.4596530
        ///32.4932990,-86.4122010
        ///32.4935470,-86.4123810
        ///32.4936790,-86.4124630
        ///32.4949880,-86.4133630
        ///32.4968000,-86.4145900
        ///32.4977400,-86.4152360
        ///32.5002390,-86.4169260
        ///32.5005430,-86.4171390
        ///32.5015450,-86.4178200
        ///32.5016780,-86.4178990
        ///32.5030740,-86.4188390
        ///32.5050300,-86.4201650
        ///32.5059040,-86.4207680
        ///32.5065800,-86.4212640
        ///32.5070640,-86.4216390
        ///32.5075400,-86.4220230
        ///32.5081290,-86.4225170
        ///32.50859 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string I65 {
            get {
                return ResourceManager.GetString("I65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highway,US280
        ///Lat,Lon
        ///32.7377294,-85.5930488
        ///32.7367160,-85.5921630
        ///32.7354210,-85.5910680
        ///32.7344030,-85.5901980
        ///32.7341190,-85.5899510
        ///32.7332460,-85.5891990
        ///32.7324250,-85.5885040
        ///32.7309920,-85.5872730
        ///32.7307100,-85.5870140
        ///32.7306700,-85.5869750
        ///32.7304770,-85.5867860
        ///32.7303000,-85.5866000
        ///32.7301280,-85.5864060
        ///32.7298380,-85.5860570
        ///32.7296390,-85.5857990
        ///32.7294510,-85.5855320
        ///32.7292340,-85.5851990
        ///32.7289950,-85.5847960
        ///32.7288060,-85.5844400
        ///32.7287040,-85.5842300
        ///32.72876 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string US280 {
            get {
                return ResourceManager.GetString("US280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vehicle {
            get {
                object obj = ResourceManager.GetObject("vehicle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
